# Generated by Django 2.1.1 on 2018-10-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickBackend', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='SOME STRING', max_length=500),
        ),
    ]
