# Generated by Django 2.1 on 2018-10-04 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickBackend', '0003_subject_credits'),
        ('quickBackend', '0003_student_password'),
    ]

    operations = [
    ]
