# Generated by Django 2.1 on 2018-10-10 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickBackend', '0006_auto_20181004_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('value', models.FloatField(default=1)),
                ('grade', models.FloatField(default=1)),
            ],
        ),
    ]
