# Generated by Django 2.1.1 on 2018-10-05 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickBackend', '0006_auto_20181004_1455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
