# Generated by Django 2.1.1 on 2018-10-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickBackend', '0007_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(default='SOME STRING', max_length=500)),
            ],
        ),
    ]
