# Generated by Django 2.1.1 on 2018-10-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickBackend', '0003_auto_20181014_0055'),
        ('quickBackend', '0008_student'),
    ]

    operations = [
    ]
